### ISSUE TITLE
Fetch AO messages

### ISSUE THREAD

**Issue by Ekzer** [ar-io/ar-io-node#312]
Hi guys,
I spent the past hours to try to run ar-io node to index AO messages, but unsuccessful still.
I just need a read-only endpoint.
I tried with these env variables : 
```
ANS104_INDEX_FILTER='{"tags":[{"name":"Bundler-App-Name", "value":"AO"}]}'
ANS104_UNBUNDLE_FILTER='{"tags":[{"name":"Bundler-App-Name", "value":"AO"}]}'
```
Unless I misunderstood the doc, would you mind help me please?
Thank you in advance

**Comment by djwhitt** [comment]
Hi @Ekzer,

These are the filters you want:
```
ANS104_UNBUNDLE_FILTER={ "or": [ { "tags": [ { "name": "Bundler-App-Name", "value": "AO" } ] }, { "isNestedBundle": true } ] }
ANS104_INDEX_FILTER={"always": true}
```

The unbundle filter tells the node to unbundle all AO bundles and nested bundles in them. The indexing filter tells the node to index all the data items in those bundles.

That said, if you run a node with this filter you will be attempting to index _a lot_ of bundles and data items (you can get feel for the volume by looking at the stats on [ao.link](https://www.ao.link/)). I think it's likely still doable on a single node, but it's not easy. We have plans to support parallel indexing across multiple nodes in the not too distant future though, so keep an eye on the change log for future release. Let us know how things go as you continue to test too.

**Comment by Ekzer** [comment]
Hi @djwhitt 
Thank you very much for your quick answer.
So I tried again but it is unsuccessful :( 
I try to run it on my Mac first (M2 MAX, 32gb), before deploying to a server. 
Here is my docker-compose and .env : 
```
services:
  io-core:
    image: ar-io-core:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./ar-io-data:/app/data
    environment:
    - ANS104_UNBUNDLE_FILTER=${ANS104_UNBUNDLE_FILTER:-}
    - ANS104_INDEX_FILTER=${ANS104_INDEX_FILTER:-}
    - ANS104_UNBUNDLE_WORKERS=${ANS104_UNBUNDLE_WORKERS:-}
    - START_HEIGHT=${START_HEIGHT:-}
    - TRUSTED_GATEWAY_URL=https://${TRUSTED_GATEWAY_HOST:-arweave.net}
    - START_WRITERS=${START_WRITERS:-true}
    - LOG_LEVEL=${LOG_LEVEL:-debug}
    - ```

.env

```
ANS104_UNBUNDLE_FILTER='{ "or": [ { "tags": [ { "name": "Bundler-App-Name", "value": "AO" } ] }, { "isNestedBundle": true } ] }'
ANS104_INDEX_FILTER='{"always":true}'
START_HEIGHT=1603940
START_WRITERS=true
LOG_LEVEL=debug
ANS104_UNBUNDLE_WORKERS=4
```

For some reasons, I can't see the unbundling process nor indexing on work in logs.
